# Generated by Django 4.0.4 on 2022-05-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipa', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.CharField(max_length=50)),
                ('jogos', models.ManyToManyField(to='futebol.encontro')),
            ],
        ),
        migrations.AddField(
            model_name='encontro',
            name='equipa1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipas1', to='futebol.equipa'),
        ),
        migrations.AddField(
            model_name='encontro',
            name='equipa2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipas2', to='futebol.equipa'),
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('jogos', models.ManyToManyField(to='futebol.encontro')),
            ],
        ),
    ]
